[workspace]
members = [
    "ctaphid-protocol",
    "linux/uhid-sys",
    "linux/uhid-tokio",
    "linux/uhid-tokio/example",
    "linux/user-daemon",
    "linux/system-daemon",
    "linux/test-authenticator",
    "u2f-core",
    "u2fhid-protocol"
]

[profile.release]
lto = true
panic = 'abort'
