[package]
authors = ["Daniel Stiner <danstiner@gmail.com>"]
name = "tokio-linux-uhid"
version = "0.4.0"
description = "Tokio-based interface to Linux UHID (user-space HID transport drivers)"
license = "MIT"

[dependencies]
bitflags = "1.1.0"
bytes = "0.4.12"
futures = "0.1.28"
mio = "0.6.19"
nix = "0.15.0"
quick-error = "1.2.2"
slog = "2.5.2"
slog-stdlog = "4.0.0"
tokio = "0.1.22"
tokio-io = "0.1.12"
tokio-proto = "0.1.1"
uhid-sys = { path = "../uhid-sys", version = "1.0.0" }
