[package]
authors = ["Daniel Stiner <danstiner@gmail.com>"]
name = "linux-uhid-tokio"
version = "0.2.0"
[dependencies]
bitflags = "1.0.1"
bytes = "0.4.6"
futures = "0.1.20"
mio = "0.6.14"
nix = "0.10.0"
quick-error = "1.2.1"
slog = "2.2.3"
slog-stdlog = "3.0.2"
tokio-core = "0.1.16"
tokio-io = "0.1.6"
tokio-proto = "0.1.1"

[dependencies.linux-uhid-sys]
path = "../uhid-sys"
